In [38]:
import math
from scipy import linalg
import numpy as np
import matplotlib.pyplot as plt 

def f(x):
    return math.sin(x/5)*math.exp(x/10)+5*math.exp(-x/2)

a = np.array([[1,  1,     1,     1], 
              [1, 4,  4**2,  4**3], 
              [1, 10, 10**2, 10**3], 
              [1, 15, 15**2, 15**3]])
b = np.array([f(1), f(4), f(10), f(15)])
x = linalg.solve(a, b)
y = np.dot(a, x)
print(b)
print(y)
print(x)
x = list(map(lambda x: str(x), x))

with open('submission-2.txt', 'w') as f:
    f.write(' '.join(x))

[3.25221687 1.74684595 2.50541641 0.63522142]
[3.25221687 1.74684595 2.50541641 0.63522142]
[ 4.36264154 -1.29552587  0.19333685 -0.00823565]
